### All blogs
http://localhost:3001/api/blogs

### Delete a blog
DELETE http://localhost:3001/api/blogs/7

### Create a new blog
POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "New blog from REST Client",
  "author": "myself",
  "url": "http://mi-blog.com"
}

### Changes the number of a blog's likes
PUT http://localhost:3001/api/blogs/7 HTTP/1.1
Content-Type: application/json

{
  "likes": 2
}